// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.0
// source: playlist.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CRUDClient is the client API for CRUD service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CRUDClient interface {
	AddSong(ctx context.Context, in *Song, opts ...grpc.CallOption) (*SongLocation, error)
	GetSong(ctx context.Context, in *SongLocation, opts ...grpc.CallOption) (*Song, error)
	UpdateSong(ctx context.Context, in *PlaylistEntry, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteSong(ctx context.Context, in *SongLocation, opts ...grpc.CallOption) (*Song, error)
}

type cRUDClient struct {
	cc grpc.ClientConnInterface
}

func NewCRUDClient(cc grpc.ClientConnInterface) CRUDClient {
	return &cRUDClient{cc}
}

func (c *cRUDClient) AddSong(ctx context.Context, in *Song, opts ...grpc.CallOption) (*SongLocation, error) {
	out := new(SongLocation)
	err := c.cc.Invoke(ctx, "/CRUD/AddSong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDClient) GetSong(ctx context.Context, in *SongLocation, opts ...grpc.CallOption) (*Song, error) {
	out := new(Song)
	err := c.cc.Invoke(ctx, "/CRUD/GetSong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDClient) UpdateSong(ctx context.Context, in *PlaylistEntry, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/CRUD/UpdateSong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRUDClient) DeleteSong(ctx context.Context, in *SongLocation, opts ...grpc.CallOption) (*Song, error) {
	out := new(Song)
	err := c.cc.Invoke(ctx, "/CRUD/DeleteSong", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CRUDServer is the server API for CRUD service.
// All implementations must embed UnimplementedCRUDServer
// for forward compatibility
type CRUDServer interface {
	AddSong(context.Context, *Song) (*SongLocation, error)
	GetSong(context.Context, *SongLocation) (*Song, error)
	UpdateSong(context.Context, *PlaylistEntry) (*emptypb.Empty, error)
	DeleteSong(context.Context, *SongLocation) (*Song, error)
	mustEmbedUnimplementedCRUDServer()
}

// UnimplementedCRUDServer must be embedded to have forward compatible implementations.
type UnimplementedCRUDServer struct {
}

func (UnimplementedCRUDServer) AddSong(context.Context, *Song) (*SongLocation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddSong not implemented")
}
func (UnimplementedCRUDServer) GetSong(context.Context, *SongLocation) (*Song, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSong not implemented")
}
func (UnimplementedCRUDServer) UpdateSong(context.Context, *PlaylistEntry) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSong not implemented")
}
func (UnimplementedCRUDServer) DeleteSong(context.Context, *SongLocation) (*Song, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSong not implemented")
}
func (UnimplementedCRUDServer) mustEmbedUnimplementedCRUDServer() {}

// UnsafeCRUDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CRUDServer will
// result in compilation errors.
type UnsafeCRUDServer interface {
	mustEmbedUnimplementedCRUDServer()
}

func RegisterCRUDServer(s grpc.ServiceRegistrar, srv CRUDServer) {
	s.RegisterService(&CRUD_ServiceDesc, srv)
}

func _CRUD_AddSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Song)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDServer).AddSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CRUD/AddSong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDServer).AddSong(ctx, req.(*Song))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUD_GetSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SongLocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDServer).GetSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CRUD/GetSong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDServer).GetSong(ctx, req.(*SongLocation))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUD_UpdateSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaylistEntry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDServer).UpdateSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CRUD/UpdateSong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDServer).UpdateSong(ctx, req.(*PlaylistEntry))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRUD_DeleteSong_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SongLocation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRUDServer).DeleteSong(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CRUD/DeleteSong",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRUDServer).DeleteSong(ctx, req.(*SongLocation))
	}
	return interceptor(ctx, in, info, handler)
}

// CRUD_ServiceDesc is the grpc.ServiceDesc for CRUD service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CRUD_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "CRUD",
	HandlerType: (*CRUDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddSong",
			Handler:    _CRUD_AddSong_Handler,
		},
		{
			MethodName: "GetSong",
			Handler:    _CRUD_GetSong_Handler,
		},
		{
			MethodName: "UpdateSong",
			Handler:    _CRUD_UpdateSong_Handler,
		},
		{
			MethodName: "DeleteSong",
			Handler:    _CRUD_DeleteSong_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "playlist.proto",
}

// SeekClient is the client API for Seek service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SeekClient interface {
	Prev(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PlaylistEntry, error)
	Next(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PlaylistEntry, error)
	NowPlaying(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NowPlayingResponse, error)
}

type seekClient struct {
	cc grpc.ClientConnInterface
}

func NewSeekClient(cc grpc.ClientConnInterface) SeekClient {
	return &seekClient{cc}
}

func (c *seekClient) Prev(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PlaylistEntry, error) {
	out := new(PlaylistEntry)
	err := c.cc.Invoke(ctx, "/Seek/Prev", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seekClient) Next(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*PlaylistEntry, error) {
	out := new(PlaylistEntry)
	err := c.cc.Invoke(ctx, "/Seek/Next", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *seekClient) NowPlaying(ctx context.Context, in *emptypb.Empty, opts ...grpc.CallOption) (*NowPlayingResponse, error) {
	out := new(NowPlayingResponse)
	err := c.cc.Invoke(ctx, "/Seek/NowPlaying", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SeekServer is the server API for Seek service.
// All implementations must embed UnimplementedSeekServer
// for forward compatibility
type SeekServer interface {
	Prev(context.Context, *emptypb.Empty) (*PlaylistEntry, error)
	Next(context.Context, *emptypb.Empty) (*PlaylistEntry, error)
	NowPlaying(context.Context, *emptypb.Empty) (*NowPlayingResponse, error)
	mustEmbedUnimplementedSeekServer()
}

// UnimplementedSeekServer must be embedded to have forward compatible implementations.
type UnimplementedSeekServer struct {
}

func (UnimplementedSeekServer) Prev(context.Context, *emptypb.Empty) (*PlaylistEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Prev not implemented")
}
func (UnimplementedSeekServer) Next(context.Context, *emptypb.Empty) (*PlaylistEntry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Next not implemented")
}
func (UnimplementedSeekServer) NowPlaying(context.Context, *emptypb.Empty) (*NowPlayingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NowPlaying not implemented")
}
func (UnimplementedSeekServer) mustEmbedUnimplementedSeekServer() {}

// UnsafeSeekServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SeekServer will
// result in compilation errors.
type UnsafeSeekServer interface {
	mustEmbedUnimplementedSeekServer()
}

func RegisterSeekServer(s grpc.ServiceRegistrar, srv SeekServer) {
	s.RegisterService(&Seek_ServiceDesc, srv)
}

func _Seek_Prev_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeekServer).Prev(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Seek/Prev",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeekServer).Prev(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seek_Next_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeekServer).Next(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Seek/Next",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeekServer).Next(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Seek_NowPlaying_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(emptypb.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SeekServer).NowPlaying(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Seek/NowPlaying",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SeekServer).NowPlaying(ctx, req.(*emptypb.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Seek_ServiceDesc is the grpc.ServiceDesc for Seek service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Seek_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Seek",
	HandlerType: (*SeekServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Prev",
			Handler:    _Seek_Prev_Handler,
		},
		{
			MethodName: "Next",
			Handler:    _Seek_Next_Handler,
		},
		{
			MethodName: "NowPlaying",
			Handler:    _Seek_NowPlaying_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "playlist.proto",
}
