name: Docker Image CI

on:
  push:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.6'
      - name: Test
        run: go test -v ./...

  build:
    needs: test
    name: Build the Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag gocloudcamp

  push:
    needs: build
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag gocloudcamp
    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
    - name: Tag & publish to GitHub Container Registry
      run: |
        IMAGE_ID=ghcr.io/${OWNER,,}/gocloudcamp
        VERSION=latest
        docker tag gocloudcamp $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
      env:
        OWNER: '${{ github.repository_owner }}'
